version: 2
executorType: docker
containerInfo:
  - image: python:3.5
    env:
      - FLASK_CONFIG=testing
      - DATABASE_URL=postgresql://ubuntu@localhost/circle_test?sslmode=disable
  - image: postgres:9.5.5
    env:
      - POSTGRES_USER=ubuntu
      - POSTGRES_DB=circle_test
      - POSTGRES_PASSWORD=
stages:
  build:
    parallel: 2
    workDir: /home/ubuntu/cci-demo-flask
    steps:
      - type: checkout
      - type: shell
        name: PWD
        command: pwd
      - type: shell
        name: LS
        command: ls -la
      - type: shell
        name: Install Yarn
        command: |
          apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
          echo "deb http://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
          apt-get update -qq
          apt-get install -y -qq yarn
      - type: cache-restore
        key: projectname-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - type: shell
        name: Install Dependencies
        command: |
          yarn
          pip install -r requirements.txt
      - type: cache-save
        key: projectname-{{ .Branch }}-{{ checksum "yarn.lock" }}
        paths:
          - "/home/ubuntu/.yarn-cache"
      - type: shell
        name: Run Tests
        command: python manage.py test --coverage
      - type: artifacts-store
        path: test-reports/coverage
        destination: reports
      - type: test-results-store
        path: "test-reports/"
      - type: deploy
        command: |
          if [[ "${CIRCLE_TAG}" =~ "/v[0-9]+(\.[0-9]+)*/" ]]; then
            echo "Run a deploy script here that only deploys based on Git tags."
          fi
